CSS stlying for submission form
Fred-Khan/Interactive_Recipe_Book pull request #17
Opened 2024-06-19 02:16 UTC by FinnL-J

Changed three files to suit rest of website:
Submission_Form.html
Submission_Form.css
Submission_Form.js

2024-06-19 13:14 UTC, Fred-Khan requested changes
You've produced brilliant work Finn! 
I would like you to tick off each task below when you get a chance and re-commit, please. Thank you.

### Recipe Submission Form
- [ ] After successfully adding an ingredient, clear the ingredient field for the next entry
- [ ] After successfully adding a step, clear the step field for the next entry
- [ ] After Confirmation and closing the modal - clear the form and ready it for a new recipe entry

### Modal form
![Submit_Recipe_Modal_Form](https://github.com/Fred-Khan/Interactive_Recipe_Book/assets/112321739/f192ea10-f100-4de8-8ccf-6aea56be8872)

- [ ] Fix up CSS for modal to appear properly and be able to see the confirm button. Maybe set **left** and **top** to use 50% to 80% of the viewport and use **transform: translate** to keep it centered on the page.
- [ ] Add a CSS to resize uploaded image to display as a standard size so the modal doesn't go oversize to fit the image.

### Confirm Button
- [ ] Set the button style to be consistent with the styling used on the main page.

2024-07-24 18:01 UTC, FinnL-J commented
Fulfilled requests

2024-08-12 21:57 UTC, Fred-Khan approved these changes
Thanks Finn! Keep up the good work!

2024-08-12 21:57 UTC, Fred-Khan commented on Submission_Form.js
> +    function clearInputs() {
FYI you can improve the `clearInputs` function in the following ways:

### 1. **Use a Loop for Similar Actions**
   Instead of repeating the `document.getElementById` calls for each input field, use a loop instead.

### 2. **Use Query Selectors for Flexibility**
   Use `querySelectorAll` with a common attribute like `data-clear` for example to select all the elements you want to clear. You can then add new elements in the future without needing to update the function.

### 3. **Avoid Hardcoding the Reset Image URL**
   Consider storing the reset image URL in a constant or using a default value that can be easily changed.

### 4. **Optimise Resetting Recipe Steps and Ingredients**
   If `recipe._ingredients` and `recipe._steps` are arrays, resetting them with `.length = 0` is slightly more efficient.

Here’s is an example of a refactored version of your code which is more maintainable and readable:

```javascript
function clearInputs() {
    const fieldsToClear = [
        "#title", 
        "#author", 
        "#description", 
        "#image-upload", 
        "#image-url", 
        "#ingredient-input", 
        "#step-input"
    ];

    fieldsToClear.forEach(selector => {
        document.querySelector(selector).value = "";
    });

    // Reset the image preview
    const imagePreview = document.getElementById("image-preview");
    if (imagePreview) {
        imagePreview.src = "#"; // Or use a default image URL
    }

    // Clear the ingredient and step lists
    document.getElementById("ingredient-list").textContent = "";
    document.getElementById("step-list").textContent = "";

    // Clear recipe ingredients and steps
    recipe._ingredients.length = 0;
    recipe._steps.length = 0;
}
```

### Explanation:
- **`fieldsToClear`:** An array of selectors to make it easier to update the fields in the future.
- **Looping through selectors:** Reduces redundancy.
- **Checking elements:** For the image preview to avoid potential null errors.
- **Array length reset:** Efficiently empties the arrays.

2024-08-12 21:58 UTC, Fred-Khan approved these changes

2024-08-12 21:58 UTC, merged