Dinner Recipe
Fred-Khan/Interactive_Recipe_Book pull request #3
Opened 2024-06-02 22:47 UTC by mixrecovery19

First Recipe - Dinner.

2024-06-11 03:17 UTC, Fred-Khan requested changes
Please amend changes as requested to gitignore, images and resolve the conflict with index.html.

2024-06-11 03:17 UTC, Fred-Khan commented on .hintrc
Please remove this file from your commit (git rm --cached .hintrc) and add to .gitignore file in your project root folder.

2024-06-11 03:17 UTC, Fred-Khan commented on index.html
This file was modified in a way that causes conflict with a previous merge. You will need to do a git pull to resolve this conflict. 

1. Do the git pull command within VS Code terminal while the project is open. 
2. You should get the option to Resolve in Merge Editor. 
3. Choose Accept Incoming and Complete Merge for this file conflict. 
4. Once conflicts are resolved, commit and push.

2024-06-11 03:17 UTC, Fred-Khan commented on recipe-chicken-with-apricot.jpg
All image assets should be in the images folder.

2024-06-11 03:33 UTC, mixrecovery19 commented on recipe-chicken-with-apricot.jpg
Moved image to images file

2024-06-11 03:37 UTC, mixrecovery19 commented on index.html
Did git pull tells me I am already up to date.

2024-06-11 03:38 UTC, mixrecovery19 commented on .hintrc
added hintrc to .gitignore, then somehow deleted it.

2024-06-12 01:15 UTC, Fred-Khan approved these changes
Well done, Michael! Looking forward to seeing the breakfast and lunch recipes.

2024-06-12 01:15 UTC, merged